# Generated by Django 5.2.7 on 2025-10-05 22:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Clinique', 'verbose_name_plural': 'Cliniques'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Médecin', 'verbose_name_plural': 'Médecins'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='receptionist',
            options={'verbose_name': 'Réceptionniste', 'verbose_name_plural': 'Réceptionnistes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom de la clinique'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='opening_hours',
            field=models.JSONField(default=dict, help_text="Horaires d'ouverture au format JSON", verbose_name="Horaires d'ouverture"),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.JSONField(default=list, help_text='Jours de disponibilité au format JSON', verbose_name='Jours disponibles'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_hours',
            field=models.JSONField(default=dict, help_text='Heures de disponibilité au format JSON', verbose_name='Heures disponibles'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='certifications',
            field=models.TextField(blank=True, null=True, verbose_name='Certifications'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.clinic', verbose_name='Clinique'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif de consultation'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID Médecin'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.TextField(verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de licence'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100, verbose_name='Spécialisation'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(verbose_name="Années d'expérience"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Groupe sanguin'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.clinic', verbose_name='Clinique'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, null=True, verbose_name='Médicaments actuels'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(max_length=100, verbose_name="Nom du contact d'urgence"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(max_length=17, verbose_name="Téléphone du contact d'urgence"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(max_length=50, verbose_name="Relation avec le contact d'urgence"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'assurance"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Fournisseur d'assurance"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True, verbose_name='Antécédents médicaux'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionists', to='core.clinic', verbose_name='Clinique'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID Employé'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='permissions',
            field=models.JSONField(default=dict, help_text='Permissions spécifiques au format JSON', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='shift_end',
            field=models.TimeField(verbose_name='Fin de service'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='shift_start',
            field=models.TimeField(verbose_name='Début de service'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='working_days',
            field=models.JSONField(default=list, help_text='Jours de travail au format JSON', verbose_name='Jours de travail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('doctor', 'Médecin'), ('receptionist', 'Réceptionniste'), ('patient', 'Patient')], default='patient', max_length=20, verbose_name="Type d'utilisateur"),
        ),
    ]
