# Generated by Django 5.2.7 on 2025-10-29 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clinic_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('checkup', 'Bilan de santé'), ('surgery', 'Chirurgie'), ('therapy', 'Thérapie'), ('vaccination', 'Vaccination'), ('dental', 'Dentaire'), ('other', 'Autre')], default='consultation', max_length=20, verbose_name='Type de service')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('duration', models.IntegerField(default=30, help_text='Durée en minutes', verbose_name='Durée')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.clinic', verbose_name='Clinique')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Date et heure du rendez-vous')),
                ('duration', models.IntegerField(default=30, help_text='Durée en minutes', verbose_name='Durée')),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('confirmed', 'Confirmé'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('cancelled', 'Annulé'), ('no_show', 'Absent')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Raison de la visite')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.clinic', verbose_name='Clinique')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.doctor', verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patient', verbose_name='Patient')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-appointment_date'],
                'indexes': [models.Index(fields=['appointment_date'], name='core_appoin_appoint_5d7cff_idx'), models.Index(fields=['patient', 'appointment_date'], name='core_appoin_patient_2cc7c6_idx'), models.Index(fields=['doctor', 'appointment_date'], name='core_appoin_doctor__9994aa_idx')],
            },
        ),
    ]
