# Generated by Django 5.1.2 on 2025-11-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_clinic_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='receptionists', to='core.service', verbose_name='Services gérés'),
        ),
    ]
