# Generated by Django 5.1.2 on 2025-11-09 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conversation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Masquée pour'),
        ),
    ]
