# Generated by Django 5.1.2 on 2025-11-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_message_deleted_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hidden_for_patient',
            field=models.BooleanField(default=False, help_text='Si True, le rendez-vous est masqué pour le patient mais reste visible pour le médecin et la réceptionniste', verbose_name='Masqué pour le patient'),
        ),
    ]
