# Generated by Django 5.1.2 on 2025-11-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appointment_hidden_for_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hidden_for_doctor',
            field=models.BooleanField(default=False, help_text='Si True, le rendez-vous est masqué pour le médecin', verbose_name='Masqué pour le médecin'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hidden_for_receptionist',
            field=models.BooleanField(default=False, help_text='Si True, le rendez-vous est masqué pour la réceptionniste', verbose_name='Masqué pour la réceptionniste'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hidden_for_patient',
            field=models.BooleanField(default=False, help_text='Si True, le rendez-vous est masqué pour le patient', verbose_name='Masqué pour le patient'),
        ),
    ]
