# Generated by Django 5.1.2 on 2025-11-12 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Diagnostic')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes et recommandations')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='active', max_length=20, verbose_name='Statut')),
                ('is_viewed_by_patient', models.BooleanField(default=False, verbose_name='Vue par le patient')),
                ('is_picked_up', models.BooleanField(default=False, verbose_name='Récupérée en pharmacie')),
                ('picked_up_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de récupération')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='core.appointment', verbose_name='Rendez-vous')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.doctor', verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200, verbose_name='Nom du médicament')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosage')),
                ('frequency', models.CharField(max_length=200, verbose_name='Fréquence')),
                ('duration', models.CharField(max_length=100, verbose_name='Durée du traitement')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='core.prescription', verbose_name='Ordonnance')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-created_at'], name='core_prescr_patient_ba2b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', '-created_at'], name='core_prescr_doctor__7b4c29_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='core_prescr_status_274d81_idx'),
        ),
    ]
